Repository The-Arjun-Thakor/Halloween, pull requests merged in 2022-10, with the labels that each got.

#1 Create profile.md
  img/profile.md
Labels: hacktoberfest-accepted

#2 Update java.js
  js/java.js
Labels: good first issue, hacktoberfest-accepted

#5 Update index.html
  index.html
Labels: good first issue

#8 Blog page css issue
  pages/blogs.html
Labels: good first issue, hacktoberfest-accepted

#9 Contact page improved
  img/Halloween-background-design-Graphics-5518640-1-580x394.jpg
  img/orangeHall.jpg
  img/pumpHall.webp
  pages/contact.html
Labels: hacktoberfest-accepted
